web:
  build: .
  command: /root/pushpin-app/config/web-run.sh
  volumes:
    - ./config/:/root/pushpin-app/config/:ro
    - ./pushpin-app/:/root/pushpin-app/
    - ./logs:/root/pushpin-app/logs/
    - /usr/local/lib/python3.4/dist-packages/django/contrib/admin/static/admin/
  expose:
    - "8000"
  links:
    - postgres
    - rabbitmq:rabbit
  environment:
    POSTGRES_PASSWORD: 'mysecretpassword'
    POSTGRES_PORT: 5432
    PUSHPIN_PASSWORD: 'test'
    # change this to change the password for pushpin
    # either way, the username is 'test' (for now)
    SECRET_KEY: 'asdfjkl;1234567890qwertyuiop'
    # CHANGE THIS TO SOMETHING SECURE WHEN YOU DEPLOY
    DEBUG: False
    # Change to True for stack traces when errors occur
    STATIC_URL: '/'
    #ALLOWED_HOSTS: "['*']"
    ALLOWED_HOSTS: "['localhost']"
    # configure this to be more restrictive on deploy

postgres:
  image: postgres
  environment:
    POSTGRES_PASSWORD: 'mysecretpassword'
    # Must be same as above, or the web container won't be able to access the db
    POSTGRES_USER: 'pushpin'
    # This is the default for the above; if you change it, set POSTGRES_USER on the web container as well to match.

nginx:
  image: nginx
  volumes:
    - ./static/:/root/static/:ro
    - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./logs:/root/logs/
    # whatever directory is before the colon is where logs will go
  volumes_from:
    - web
  ports:
    - "8080:80"
    # whatever port you put before the colon will be where pushpin-web is served
  links:
    - web

rabbitmq:
  image: rabbitmq
  #environment:
    #RABBITMQ_NODENAME: rabbitmq-server

celery:
  build: .
  command: /root/pushpin-app/config/celery-run.sh
  volumes:
    - ./config/:/root/pushpin-app/config/:ro
    - ./pushpin-app/:/root/pushpin-app/:ro
    - ./logs:/root/pushpin-app/logs/
  links:
    - rabbitmq:rabbit
    - postgres
  environment:
    POSTGRES_PASSWORD: 'mysecretpassword'
    # Again, must match the settings on the postgres container
    POSTGRES_PORT: 5432
    DEBUG: False
    # Change to True for stack traces when errors occur
    PUSHPIN_LOG_PATH: '/root/pushpin-app/logs/celery.log'
